### ISSUE TITLE
Cannot initialize a 1x1 Grid

### ISSUE THREAD

**Issue by bwj-GitHub** [bwj-GitHub/traffic-simulator#16]
Beginning simulation!
+LightEvent(30.0, TrafficLight(Intersection(0, 0), true), GREEN)
+LightEvent(25.0, TrafficLight(Intersection(0, 0), false), YELLOW)
+CarSpawnEvent(0.0)
-CarSpawnEvent(0.0)
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at traffic.PathFactory.newPath(PathFactory.java:59)
	at traffic.CarFactory.newCar(CarFactory.java:23)
	at grid.TrafficGrid.handleCarSpawnEvent(TrafficGrid.java:144)
	at grid.TrafficGrid.handleEvent(TrafficGrid.java:129)
	at simulator.TrafficSimulator.run(TrafficSimulator.java:59)
	at simulator.TrafficSimulator.main(TrafficSimulator.java:92)

**Comment by bwj-GitHub** [comment]
No longer using brandon's version of the simulator.
